
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.unit
{ 
    public enum EUnitType
    {
        /// <summary>
        /// 蓝晶族
        /// </summary>
        BLUE = 1,
        /// <summary>
        /// 赤焰族
        /// </summary>
        RED = 2,
        /// <summary>
        /// 翠叶族
        /// </summary>
        GREEN = 3,
        /// <summary>
        /// 金雷族
        /// </summary>
        YELLOW = 4,
        /// <summary>
        /// 樱粉族
        /// </summary>
        PINK = 5,
        /// <summary>
        /// 黯渊族
        /// </summary>
        BLACK = 99,
    }

} 

