
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.unit
{
public sealed partial class Unit : Luban.BeanBase
{
    public Unit(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        UnitRace = (unit.EUnitRace)_buf.ReadInt();
        Quality = (EQuality)_buf.ReadInt();
    }

    public static Unit DeserializeUnit(ByteBuf _buf)
    {
        return new unit.Unit(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 单位种族
    /// </summary>
    public readonly unit.EUnitRace UnitRace;
    /// <summary>
    /// 稀有度
    /// </summary>
    public readonly EQuality Quality;
   
    public const int __ID__ = -518455346;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "unitRace:" + UnitRace + ","
        + "quality:" + Quality + ","
        + "}";
    }
}
}

