
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum EItemType
    {
        /// <summary>
        /// 资源
        /// </summary>
        RESOURCE = 1,
        /// <summary>
        /// 物品
        /// </summary>
        GOODS = 2,
    }

} 

