
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum EQuality
    {
        /// <summary>
        /// 普通
        /// </summary>
        WHITE = 1,
        /// <summary>
        /// 稀有
        /// </summary>
        BLUE = 2,
        /// <summary>
        /// 史诗
        /// </summary>
        PURPLE = 3,
        /// <summary>
        /// 传说
        /// </summary>
        ORANGE = 4,
    }

} 

