
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class GlobalConfig : Luban.BeanBase
{
    public GlobalConfig(ByteBuf _buf) 
    {
        EnergyMax = _buf.ReadInt();
        LevelEnergyConsume = _buf.ReadInt();
        CoinPerLevel = _buf.ReadInt();
        FirstClearMultiplier = _buf.ReadFloat();
        EnergyReturnRate = _buf.ReadFloat();
        AdMultiplier = _buf.ReadFloat();
        DailyCheckinRewardId = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); AdRewardPackIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AdRewardPackIds.Add(_e0);}}
    }

    public static GlobalConfig DeserializeGlobalConfig(ByteBuf _buf)
    {
        return new GlobalConfig(_buf);
    }

    /// <summary>
    /// 体力上限
    /// </summary>
    public readonly int EnergyMax;
    /// <summary>
    /// 推关消耗体力
    /// </summary>
    public readonly int LevelEnergyConsume;
    /// <summary>
    /// 每关递增金币
    /// </summary>
    public readonly int CoinPerLevel;
    /// <summary>
    /// 首通倍率
    /// </summary>
    public readonly float FirstClearMultiplier;
    /// <summary>
    /// 体力返还比例
    /// </summary>
    public readonly float EnergyReturnRate;
    /// <summary>
    /// 广告倍率
    /// </summary>
    public readonly float AdMultiplier;
    /// <summary>
    /// 每日签到奖励id
    /// </summary>
    public readonly int DailyCheckinRewardId;
    /// <summary>
    /// 广告礼包ID
    /// </summary>
    public readonly System.Collections.Generic.List<int> AdRewardPackIds;
   
    public const int __ID__ = -958250779;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "energyMax:" + EnergyMax + ","
        + "levelEnergyConsume:" + LevelEnergyConsume + ","
        + "coinPerLevel:" + CoinPerLevel + ","
        + "firstClearMultiplier:" + FirstClearMultiplier + ","
        + "energyReturnRate:" + EnergyReturnRate + ","
        + "adMultiplier:" + AdMultiplier + ","
        + "dailyCheckinRewardId:" + DailyCheckinRewardId + ","
        + "adRewardPackIds:" + Luban.StringUtil.CollectionToString(AdRewardPackIds) + ","
        + "}";
    }
}
}

