
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class LevelChest : Luban.BeanBase
{
    public LevelChest(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        LevelId = _buf.ReadInt();
        RewardId = _buf.ReadInt();
    }

    public static LevelChest DeserializeLevelChest(ByteBuf _buf)
    {
        return new LevelChest(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 关卡id
    /// </summary>
    public readonly int LevelId;
    /// <summary>
    /// 奖励id
    /// </summary>
    public readonly int RewardId;
   
    public const int __ID__ = -2120627715;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "levelId:" + LevelId + ","
        + "rewardId:" + RewardId + ","
        + "}";
    }
}
}

