
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class RewardEntry : Luban.BeanBase
{
    public RewardEntry(ByteBuf _buf) 
    {
        ItemType = _buf.ReadInt();
        ItemId = _buf.ReadInt();
        Amount = _buf.ReadInt();
    }

    public static RewardEntry DeserializeRewardEntry(ByteBuf _buf)
    {
        return new RewardEntry(_buf);
    }

    /// <summary>
    /// 物品类型(1=Resource)
    /// </summary>
    public readonly int ItemType;
    /// <summary>
    /// 物品ID(对应ResourceType枚举值)
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 数量
    /// </summary>
    public readonly int Amount;
   
    public const int __ID__ = -1752721821;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "itemType:" + ItemType + ","
        + "itemId:" + ItemId + ","
        + "amount:" + Amount + ","
        + "}";
    }
}
}

