
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Reward : Luban.BeanBase
{
    public Reward(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        {int n0 = _buf.ReadSize(); RewardItems = new System.Collections.Generic.List<RewardEntry>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { RewardEntry _e0;  _e0 = global::GameConfig.RewardEntry.DeserializeRewardEntry(_buf); RewardItems.Add(_e0);}}
    }

    public static Reward DeserializeReward(ByteBuf _buf)
    {
        return new Reward(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 奖励列表
    /// </summary>
    public readonly System.Collections.Generic.List<RewardEntry> RewardItems;
   
    public const int __ID__ = -1850459313;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in RewardItems) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "rewardItems:" + Luban.StringUtil.CollectionToString(RewardItems) + ","
        + "}";
    }
}
}

