
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    /// <summary>
    /// 角色单位
    /// </summary>
    private TbUnit m_TbUnit;
    public TbUnit TbUnit 
    {
        get
        {
            if (m_TbUnit == null)
            {
                m_TbUnit = new TbUnit(defaultLoader("tbunit"));
                m_TbUnit.ResolveRef(this);
            }
            return m_TbUnit;
        }
        set
        {
            m_TbUnit = value;
            m_TbUnit.ResolveRef(this);
        }
    }
    /// <summary>
    /// 全局配置
    /// </summary>
    private TbGlobalConfig m_TbGlobalConfig;
    public TbGlobalConfig TbGlobalConfig 
    {
        get
        {
            if (m_TbGlobalConfig == null)
            {
                m_TbGlobalConfig = new TbGlobalConfig(defaultLoader("tbglobalconfig"));
                m_TbGlobalConfig.ResolveRef(this);
            }
            return m_TbGlobalConfig;
        }
        set
        {
            m_TbGlobalConfig = value;
            m_TbGlobalConfig.ResolveRef(this);
        }
    }
    /// <summary>
    /// 资源表
    /// </summary>
    private TbResource m_TbResource;
    public TbResource TbResource 
    {
        get
        {
            if (m_TbResource == null)
            {
                m_TbResource = new TbResource(defaultLoader("tbresource"));
                m_TbResource.ResolveRef(this);
            }
            return m_TbResource;
        }
        set
        {
            m_TbResource = value;
            m_TbResource.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}
