
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    /// <summary>
    /// 角色单位
    /// </summary>
    private unit.TbUnit m_TbUnit;
    public unit.TbUnit TbUnit 
    {
        get
        {
            if (m_TbUnit == null)
            {
                m_TbUnit = new unit.TbUnit(defaultLoader("unit_tbunit"));
                m_TbUnit.ResolveRef(this);
            }
            return m_TbUnit;
        }
        set
        {
            m_TbUnit = value;
            m_TbUnit.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}
