
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 全局配置
/// </summary>
public partial class TbGlobalConfig
{

     private readonly GlobalConfig _data;

     public GlobalConfig Data => _data;

    public TbGlobalConfig(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        if (n != 1) throw new SerializationException("table mode=one, but size != 1");
        _data = global::GameConfig.GlobalConfig.DeserializeGlobalConfig(_buf);
    }


    /// <summary>
    /// 体力上限
    /// </summary>
     public int EnergyMax => _data.EnergyMax;
    /// <summary>
    /// 推关消耗体力
    /// </summary>
     public int LevelEnergyConsume => _data.LevelEnergyConsume;
    /// <summary>
    /// 每关递增金币
    /// </summary>
     public int CoinPerLevel => _data.CoinPerLevel;
    /// <summary>
    /// 首通倍率
    /// </summary>
     public float FirstClearMultiplier => _data.FirstClearMultiplier;
    /// <summary>
    /// 体力返还比例
    /// </summary>
     public float EnergyReturnRate => _data.EnergyReturnRate;
    /// <summary>
    /// 广告倍率
    /// </summary>
     public float AdMultiplier => _data.AdMultiplier;
    /// <summary>
    /// 每日签到奖励id
    /// </summary>
     public int DailyCheckinRewardId => _data.DailyCheckinRewardId;
    
    public void ResolveRef(Tables tables)
    {
        _data.ResolveRef(tables);
    }
}

}

