
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 物品表
/// </summary>
public partial class TbGoods
{
    private readonly System.Collections.Generic.Dictionary<int, Goods> _dataMap;
    private readonly System.Collections.Generic.List<Goods> _dataList;
    
    public TbGoods(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Goods>(n);
        _dataList = new System.Collections.Generic.List<Goods>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Goods _v;
            _v = global::GameConfig.Goods.DeserializeGoods(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Goods> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Goods> DataList => _dataList;

    public Goods GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Goods Get(int key) => _dataMap[key];
    public Goods this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

