
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 推关激励奖励
/// </summary>
public partial class TbLevelChest
{
    private readonly System.Collections.Generic.Dictionary<int, LevelChest> _dataMap;
    private readonly System.Collections.Generic.List<LevelChest> _dataList;
    
    public TbLevelChest(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, LevelChest>(n);
        _dataList = new System.Collections.Generic.List<LevelChest>(n);
        for(int i = n ; i > 0 ; --i)
        {
            LevelChest _v;
            _v = global::GameConfig.LevelChest.DeserializeLevelChest(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, LevelChest> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<LevelChest> DataList => _dataList;

    public LevelChest GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public LevelChest Get(int key) => _dataMap[key];
    public LevelChest this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

