
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
/// <summary>
/// 资源表
/// </summary>
public partial class TbResource
{
    private readonly System.Collections.Generic.Dictionary<int, Resource> _dataMap;
    private readonly System.Collections.Generic.List<Resource> _dataList;
    
    public TbResource(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Resource>(n);
        _dataList = new System.Collections.Generic.List<Resource>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Resource _v;
            _v = global::GameConfig.Resource.DeserializeResource(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Resource> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Resource> DataList => _dataList;

    public Resource GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Resource Get(int key) => _dataMap[key];
    public Resource this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

